sudo: required
cache:
  directories:
    - $HOME/.m2
language: java
jdk:
  - oraclejdk11
  - openjdk11
os:
  - linux
branches:
  only:
  - master
before_script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - _ci/run-tags.sh
install: true